"""add company_id to analysis_jobs

Revision ID: 3683c199aadd
Revises: 774ad5b33889
Create Date: 2026-05-10 14:18:36.494587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3683c199aadd'
down_revision: Union[str, Sequence[str], None] = '774ad5b33889'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_jobs', sa.Column('company_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_jobs', 'company_id')
    # ### end Alembic commands ###
