"""update_extract_task_and_meeting_sumary_models

Revision ID: 970b4606a86d
Revises: ae04c56a72d7
Create Date: 2026-05-05 21:09:25.633426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '970b4606a86d'
down_revision: Union[str, Sequence[str], None] = 'ae04c56a72d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extracted_tasks', sa.Column('manually_assigned', sa.Boolean(), nullable=True))
    op.add_column('extracted_tasks', sa.Column('rejected_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('extracted_tasks', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.add_column('meeting_summaries', sa.Column('is_edited', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting_summaries', 'is_edited')
    op.drop_column('extracted_tasks', 'rejection_reason')
    op.drop_column('extracted_tasks', 'rejected_at')
    op.drop_column('extracted_tasks', 'manually_assigned')
    # ### end Alembic commands ###
