"""init ai analysis tables

Revision ID: ae04c56a72d7
Revises: 
Create Date: 2026-04-22 10:22:20.576564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae04c56a72d7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('transcript_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extracted_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_job_id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('raw_assignee_text', sa.String(length=255), nullable=True),
    sa.Column('resolved_user_id', sa.UUID(), nullable=True),
    sa.Column('deadline_raw', sa.String(length=255), nullable=True),
    sa.Column('deadline_date', sa.DATE(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source_utterance_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('confirmed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['analysis_job_id'], ['analysis_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_job_id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('edited_summary', sa.Text(), nullable=True),
    sa.Column('key_decisions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attendees_mentioned', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('topics_covered', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['analysis_job_id'], ['analysis_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting_summaries')
    op.drop_table('extracted_tasks')
    op.drop_table('analysis_jobs')
    # ### end Alembic commands ###
