"""add context to transcription_corrections

Revision ID: 57730085a48f
Revises: a25704ea7d74
Create Date: 2026-05-16 10:41:59.780205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57730085a48f'
down_revision: Union[str, Sequence[str], None] = 'a25704ea7d74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcription_corrections', sa.Column('context', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcription_corrections', 'context')
    # ### end Alembic commands ###
