"""add trello_api_key to companies

Revision ID: bd685798d662
Revises: 286862053a9c
Create Date: 2026-05-01 21:34:49.868526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd685798d662'
down_revision: Union[str, Sequence[str], None] = '286862053a9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('trello_api_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'trello_api_key')
    # ### end Alembic commands ###
