"""add company_id

Revision ID: 810bfc87d2d5
Revises: 910de0239ec0
Create Date: 2026-05-15 21:05:45.414120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '810bfc87d2d5'
down_revision: Union[str, Sequence[str], None] = '910de0239ec0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcription_jobs', sa.Column('company_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcription_jobs', 'company_id')
    # ### end Alembic commands ###
