"""add utterance  field

Revision ID: 910de0239ec0
Revises: 43c57a371b2a
Create Date: 2026-04-19 23:23:42.549853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '910de0239ec0'
down_revision: Union[str, Sequence[str], None] = '43c57a371b2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utterances', sa.Column('original_text', sa.Text(), nullable=True))
    op.add_column('utterances', sa.Column('is_edited', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utterances', 'is_edited')
    op.drop_column('utterances', 'original_text')
    # ### end Alembic commands ###
